layout_spectrum: 0.8320428
typography_spectrum: 1
color:
  lightness: 0.6005455
  brandStrength: 0.9867103
  saturation: 0.2255957
  rhythmicContrast: 0.927153
  brandColors:
    - '#030303'
    - '#FBFAFB'
    - '#6E6663'
    - '#B4B4B4'
    - '#65FB87'
name: A Woytovich Motion
